# vim:ft=kitty
#: This is a template that can be used to create new kitty themes.
#: Theme files should start with a metadata block consisting of
#: lines beginning with ##. All metadata fields are optional.

## name: The name of the theme (if not present, derived from filename)
## author: The name of the theme author
## license: The license information
## upstream: A URL pointing to the location of this file upstream for auto-updates
## blurb: A description of this theme. This must be the
## last item in the metadata and can continue over multiple lines.

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: The basic colors

# foreground                      #527481
foreground                      #f7efd8
# background                      #0f3b3a
background                      #053230


selection_foreground            #f7efd8
selection_background            #969c46


#: Cursor colors

cursor                          #ffffff
cursor_text_color               #111111


#: URL underline color when hovering with mouse

url_color                       #527481


#: kitty window border colors and terminal bell colors

# active_border_color             #00ff00
# inactive_border_color           #cccccc
# bell_border_color               #ff5a00
# visual_bell_color               none


#: OS Window titlebar colors

# wayland_titlebar_color          system
# macos_titlebar_color            system


#: Tab bar colors

# active_tab_foreground           #000
# active_tab_background           #eee
# inactive_tab_foreground         #444
# inactive_tab_background         #999
# tab_bar_background              none
# tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

# mark1_foreground black
# mark1_background #98d3cb
# mark2_foreground black
# mark2_background #f2dcd3
# mark3_foreground black
# mark3_background #f274bc


#: The basic 16 colors

#: black
color0 #155352
# color8 #767676

#: red
color1 #a14334
color9 #d74200

#: green
color2  #438952
color10 #009403

#: yellow
color3  #cfc041
color11 #98875f

#: blue
color4  #448fb6
color12 #0096ff

#: magenta
color5  #da5bd6
color13 #b154cf

#: cyan
color6  #77bfcf
color14 #40a4b9

#: white
color7  #b1c9c3
color15 #ffffff


#: You can set the remaining 240 colors as color16 to color255.
