# Get rid of the sill random quote that appears on the desktop
splash = false

# preload =/home/pj/Pictures/wallpaper/9042-greenhouse-door-plants-green-dark-4k.jpg
preload = /home/pj/Pictures/wallpaper/crop/bottom.jpg
#if more than one preload is desired then continue to preload other backgrounds
# preload =/home/pj/Pictures/wallpaper/1b89ec5d2a523a4c3a76638165511455.jpeg
preload = /home/pj/Pictures/wallpaper/crop/top.jpg
# # .. more preloads

#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = DP-1,/home/pj/Pictures/wallpaper/crop/bottom.jpg
#if more than one monitor in use, can load a 2nd image
wallpaper = DP-3,/home/pj/Pictures/wallpaper/crop/top.jpg
# .. more monitors
