general {
    lock_cmd = pidof hyprlock || hyprlock # avoids multiple instances of lockscreen
    unlock_cmd = notify-send "unlock!"
    before_sleep_cmd = notify-send "before_sleep!"
    after_sleep_cmd = notify-send "after_sleep!"
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# Add as many listeners as you want.  If on-timeout or on-resume is omitted then
# that command will simply be ignored.
listener {
    timeout = 500 # in seconds
    on-timeout = lock_cmd
    #on-resume = notify-send "back!"
}
