general {
    lock_cmd = pidof hyprlock || hyprlock # avoids multiple instances of lockscreen
    unlock_cmd = notify-send "unlock!"
    before_sleep_cmd = notify-send "before_sleep!"
    after_sleep_cmd = notify-send "after_sleep!"
    ignore_dbus_inhibit = false
}

# Add as many listeners as you want.  If on-timeout or on-resume is omitted then
# that command will simply be ignored.

# Using hyprlock as a screen-blanking screensaver that doesn't actually lock
listener {
    timeout = 500 # in seconds
    on-timeout = loginctl lock-session
    on-resume = pkill -USR1 hyprlock
}
# listener {
#     timeout = 10 # in seconds
#     on-timeout = mpv --really-quiet --no-audio --no-stop-screensaver --loop=inf --autofit=100% --fs --panscan=1 ~/Videos/screensaver/11374537-uhd_3840_2160_30fps.mp4 &; echo $! >> /tmp/screensaver.pid
#     on-resume = kill -9 $(cat /tmp/screensaver.pid)
# }
